# Generated by Django 4.0.5 on 2022-06-18 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csw', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='character_ref',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, null=True, verbose_name='Name')),
                ('address', models.CharField(max_length=70, null=True, verbose_name='Address')),
                ('name1', models.CharField(max_length=70, null=True, verbose_name='Name')),
                ('occupation', models.CharField(max_length=70, null=True, verbose_name='Occupation')),
                ('business_address', models.CharField(max_length=70, null=True, verbose_name='Business Address')),
                ('email', models.EmailField(max_length=70, null=True, verbose_name='Email')),
                ('capacity', models.CharField(max_length=70, null=True, verbose_name='Capacity In Which You Know The Applicant')),
            ],
        ),
        migrations.CreateModel(
            name='education_and_training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_of_your_training', models.CharField(max_length=70, null=True, verbose_name='Title Of Your Training')),
                ('start_date', models.DateField(null=True, verbose_name='Start Date')),
                ('end_date', models.DateField(null=True, verbose_name='End Date')),
                ('name_of_provider', models.CharField(max_length=70, null=True, verbose_name='Name Of Provider')),
                ('certificates', models.FileField(null=True, upload_to='', verbose_name='Certificates')),
                ('city', models.CharField(max_length=70, null=True, verbose_name='City/Town')),
                ('country', models.CharField(max_length=70, null=True, verbose_name='Country')),
                ('name', models.CharField(max_length=70, null=True, verbose_name='Name')),
                ('job_title', models.CharField(max_length=70, null=True, verbose_name='Job Title')),
                ('telephone_number', models.CharField(max_length=70, null=True, verbose_name='Telephone Number')),
                ('email', models.EmailField(max_length=70, null=True, verbose_name='Email')),
                ('title_of_your_training1', models.CharField(max_length=70, null=True, verbose_name='Title Of Your Training')),
                ('start_date1', models.DateField(max_length=70, null=True, verbose_name='Start Date')),
                ('end_date1', models.DateField(max_length=70, null=True, verbose_name='End Date')),
                ('name_of_pro', models.CharField(max_length=70, null=True, verbose_name='Name Of Provider')),
                ('address', models.CharField(max_length=700, null=True, verbose_name='Address')),
                ('town', models.CharField(max_length=70, null=True, verbose_name='City/Town')),
                ('country1', models.CharField(max_length=70, null=True, verbose_name='Country')),
            ],
        ),
        migrations.CreateModel(
            name='practise_outside',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_of_practise', models.CharField(blank=True, max_length=70, null=True, verbose_name='Name Of Country Practice')),
                ('regulatory_body', models.CharField(blank=True, max_length=70, null=True, verbose_name='Regulatory Body')),
                ('regulatory_number', models.CharField(blank=True, max_length=70, null=True, verbose_name='Regulatory Number')),
                ('organisation', models.CharField(blank=True, max_length=70, null=True, verbose_name='Organisation')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('post', models.CharField(blank=True, max_length=70, null=True, verbose_name='Post')),
                ('address', models.CharField(blank=True, max_length=70, null=True, verbose_name='Address')),
                ('city', models.CharField(blank=True, max_length=70, null=True, verbose_name='City/Town')),
                ('country', models.CharField(max_length=70, null=True, verbose_name='Country')),
                ('name_of_manager', models.CharField(blank=True, max_length=70, null=True, verbose_name='Name Of Manager')),
                ('mobile_number', models.CharField(blank=True, max_length=70, null=True, verbose_name='Mobile Number')),
                ('email', models.EmailField(blank=True, max_length=70, null=True, verbose_name='Email')),
                ('any_discipinary', models.CharField(blank=True, choices=[('N', 'NO'), ('Y', 'Yes'), ('I', 'If Yes Give Reason')], max_length=20, null=True, verbose_name='Faced Any Disciplinary Action')),
            ],
        ),
        migrations.CreateModel(
            name='pst_five_work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation', models.CharField(blank=True, max_length=70, null=True, verbose_name='Organisation')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('post', models.CharField(blank=True, max_length=70, null=True, verbose_name='Post')),
                ('address', models.CharField(blank=True, max_length=70, null=True, verbose_name='Address')),
                ('town', models.CharField(blank=True, max_length=70, null=True, verbose_name='City/Town')),
                ('country1', models.CharField(blank=True, max_length=70, null=True, verbose_name='Country')),
                ('name_of_manager', models.CharField(blank=True, max_length=70, null=True, verbose_name='Name Of Manager')),
                ('mobile_number', models.CharField(blank=True, max_length=70, null=True, verbose_name='Mobile Number')),
                ('email_address', models.EmailField(blank=True, max_length=70, null=True, verbose_name='Email Address')),
            ],
        ),
        migrations.CreateModel(
            name='rivate_practice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jurisdiction', models.CharField(max_length=70, null=True, verbose_name='Jurisdiction')),
                ('area_of_practice', models.CharField(max_length=70, null=True, verbose_name='Area of Practice eg Counselling')),
                ('name_of_practise', models.CharField(max_length=70, null=True, verbose_name='Name Of Practise')),
                ('address', models.CharField(max_length=70, null=True, verbose_name='Address')),
                ('mobile_number', models.CharField(max_length=70, null=True, verbose_name='Mobile Number')),
                ('email', models.EmailField(max_length=70, null=True, verbose_name='Email')),
                ('any_discipinary', models.CharField(choices=[('N', 'NO'), ('Y', 'Yes'), ('I', 'If Yes Give Reason')], max_length=20, null=True, verbose_name='Have you ever practiced as a Registered Social Worker')),
            ],
        ),
        migrations.CreateModel(
            name='Work_contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation', models.CharField(max_length=70, null=True, verbose_name='Organisation')),
                ('department', models.CharField(max_length=70, null=True, verbose_name='Department')),
                ('address', models.CharField(max_length=70, null=True, verbose_name='Address')),
                ('city', models.CharField(max_length=70, null=True, verbose_name='City')),
                ('country', models.CharField(max_length=70, null=True, verbose_name='Country')),
                ('mobile_number', models.CharField(max_length=70, null=True, verbose_name='Mobile Number')),
                ('email_address', models.EmailField(max_length=70, null=True, verbose_name='Email Address')),
            ],
        ),
        migrations.RemoveField(
            model_name='person',
            name='description',
        ),
        migrations.AddField(
            model_name='person',
            name='Gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=20, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='person',
            name='country_of_birth',
            field=models.CharField(max_length=80, null=True, verbose_name='Country Of Birth'),
        ),
        migrations.AddField(
            model_name='person',
            name='date_of_birth',
            field=models.DateField(null=True, verbose_name='Date of Birth'),
        ),
        migrations.AddField(
            model_name='person',
            name='first_name',
            field=models.CharField(max_length=50, null=True, verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='person',
            name='national_id_number',
            field=models.CharField(max_length=40, null=True, verbose_name='National ID Number'),
        ),
        migrations.AddField(
            model_name='person',
            name='nationality',
            field=models.CharField(max_length=50, null=True, verbose_name='Nationality'),
        ),
        migrations.AddField(
            model_name='person',
            name='passport_photo',
            field=models.ImageField(blank=True, default='profile1.png', null=True, upload_to='', verbose_name='Passport Photo'),
        ),
        migrations.AddField(
            model_name='person',
            name='surname',
            field=models.CharField(max_length=70, null=True, verbose_name='Surname'),
        ),
        migrations.AlterField(
            model_name='person',
            name='title',
            field=models.IntegerField(choices=[(1, 'Mr'), (2, 'Mrs'), (3, 'Miss'), (4, 'Other')], null=True, verbose_name='Title'),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('house_number', models.CharField(max_length=70, null=True, verbose_name='House Number')),
                ('mobile_number', models.CharField(max_length=70, null=True, verbose_name='Mobile Number')),
                ('city', models.CharField(max_length=70, null=True, verbose_name='Town/City Of Birth')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('person', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='csw.person')),
            ],
        ),
    ]
