# FOR USER MODEL

MANAGER = 'MANAGER'
ADMIN = 'Admin'
MEMBER = 'Member'
STUDENT = 'Student'

ROLES = (
    (MANAGER, MANAGER),
    (ADMIN, ADMIN),
    (MEMBER, MEMBER),
    (STUDENT, STUDENT)
)

# CHOICES FOR REFFERAL MODEL

REGISTERED = 'Registered'
RENEWED = 'Renewed'
EXPIRED = 'Expired'
IN_PROGRESS = 'In progress'

REGISTRATION_STATUS = (
    (REGISTERED, REGISTERED),
    (RENEWED, RENEWED),
    (EXPIRED, EXPIRED),
    (IN_PROGRESS, IN_PROGRESS)
)