# Generated by Django 3.2 on 2022-06-15 19:30

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220615_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_number', models.CharField(blank=True, max_length=10)),
                ('next_of_kin', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField(validators=[django.core.validators.MaxValueValidator(datetime.date(2022, 6, 15))])),
                ('age', models.IntegerField(blank=True)),
                ('town', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('national_id', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='prescription',
            name='end_datetime',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.datetime(2022, 6, 15, 19, 30, 19, 439741, tzinfo=utc))]),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='start_datetime',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.datetime(2022, 6, 15, 19, 30, 19, 439685, tzinfo=utc))]),
        ),
    ]
